[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools", "wheel"]

[project]
name = "quac"
description = "Quantitative Attribution with Counterfactuals"
readme = "README.md"
requires-python = ">=3.10,<3.13"
classifiers = ["Programming Language :: Python :: 3"]
keywords = []
license = { text = "BSD 3-Clause License" }
authors = [
  { name = "Diane Adjavon", email = "adjavond@hhmi.org" },
  { name = "Jan Funke", email = "funkej@hhmi.org" },
]
dynamic = ["version"]
dependencies = [
  "captum",
  "numpy>=2.0",
  "torch>=2.4.0,<2.5",
  "torchvision>=0.19.0",
  "funlib-learn-torch",
  "opencv-python",
  "pydantic",
  "scipy",
  "scikit-learn",
  "imageio>=2.37.0,<3",
  "scikit-image>=0.24.0,<0.25",
  "pandas>=2.2.3,<3",
  "pyyaml"
]

[project.optional-dependencies]
dev = ['pytest', 'black', 'mypy', 'pdoc', 'pre-commit']
web = ['flask>=2.0.0', 'werkzeug>=2.0.0']
docs = [
  "ipykernel",
  "jupyter_sphinx",
  "sphinx_autodoc_typehints",
  "sphinx_rtd_theme",
  "furo",
  "sphinx_togglebutton",
  "sphinxcontrib_jquery",
  "sphinxcontrib-email",
  "sphinx>6",
  "tomli",
  "myst-parser",
  "sphinx-copybutton",
  "sphinx-design",
]

[project.urls]
homepage = "https://funkelab.github.io/quac/"
repository = "https://github.com/funkelab/quac"

[tool.setuptools.dynamic]
version = { attr = "quac.__version__" }

[tool.uv]
dev-dependencies = [
    "pytest",
    "black", 
    "mypy",
    "pdoc",
    "pre-commit"
]

[tool.uv.sources]
# Handle the git dependency for funlib.learn.torch
funlib-learn-torch = { git = "https://github.com/funkelab/funlib.learn.torch" }

[tool.mypy]
python_version = "3.10"
